### ISSUE TITLE
JupyterHub with containers

### ISSUE THREAD

**Issue by fnattino** [RS-DAT/JupyterDaskOnSRC#19]
Can we create a JupyterHub instance on SRC that uses custom container images to instantiate Lab sessions?

**Comment by fnattino** [comment]
Maybe a first attempt could be based on using the pang notebook image: https://github.com/pangeo-data/pangeo-docker-images

**Comment by fnattino** [comment]
JupyterHub Docker Spawner: https://jupyterhub-dockerspawner.readthedocs.io/en/latest/

**Comment by fnattino** [comment]
We should maybe start by having a look at the JupyterHub catalog items on SRC. Do any of these already provide an implementation that can work with containers? Some information could maybe be found on the SRC docs: https://servicedesk.surf.nl/wiki/display/WIKI/SURF+Research+Cloud

**Comment by SarahAlidoost** [comment]
According to [doc](https://servicedesk.surf.nl/wiki/display/WIKI/Start+a+simple+workspace#Startasimpleworkspace-workspaceApplications), there is a section "`Workspace parameters`" to set container info. However, it is not clear which catalog items have this section. This section is not available for JupyterHub or Ubuntu. 
I also found documentation on creating [a Docker Compose catalog item](https://servicedesk.surf.nl/wiki/display/WIKI/Creating+a+Docker+Compose+catalog+item) on SRC.

**Comment by SarahAlidoost** [comment]
To use JupyterHub Docker Spawne, see valid docker images at [how-to-pick-a-docker-image](https://jupyterhub-dockerspawner.readthedocs.io/en/latest/docker-image.html#how-to-pick-a-docker-image), examples are [here](https://quay.io/organization/jupyter). Example `jupyter_config` file is [here](https://github.com/jupyterhub/dockerspawner/blob/749daed9094629c7df8db60b38b7a162b5f03d4c/examples/oauth/jupyterhub_config.py).

**Comment by SarahAlidoost** [comment]
- [ ] test pangeo image locally
- [ ] test config file on SRC locally
- [ ] check if container can be paused and not deleted
- [ ] create catalog item on SRC, (in a different repo)
